#!/usr/bin/python3
""" Factorize as many numbers as possible into a product of two smaller numbers. """

# library to get arguments
import sys


# fn unpack number factorial
def factorize():
    """
     A function to search File and factorize the given set of numbers into two prime numbers (format n = p * q).
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber % 2 == 0:
                        print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                        continue
                i = 3
                while i < revnumber // 2:
                    if revnumber % i == 0:
                        print("{}={}*{}".format(revnumber, revnumber // i, i))
                        break
                    i = i + 2
                if i == (revnumber // 2) + 1:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except (IndexError):
        pass


# Autostart
factorize()
